---
events:
  - event: push
    branch: master
    build: bash -c "env > /tmp/done2"
    upload: touch /tmp/done3
    on_success: success
    on_failure: failure
notifications:
    success:
        to:
          - "@Igor.Chubin"
        message: success
    failure:
        to:
          - "@Igor.Chubin"
        message: failure
